name: gitartwork from a contribution graph
on:
  push:
  schedule:
    - cron: '* */24 * * *'
  workflow_dispatch:
jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jasineri/gitartwork@v1
        with:
          # Use this username's contribution graph
          user_name: brian-weloba
          # Text on contribution graph
          text: bweloba
      - uses: jasineri/simple-push-action@v1